# comments are harmless, so you can copy/paste this content as-is
# downloading the following image will give java8 and maven both
FROM maven:3.5.0-jdk-8
# don't fret about the following
WORKDIR /apps
COPY . /apps
CMD tail -f /dev/null

